### ISSUE TITLE
How to install and use this program

### ISSUE THREAD

**Issue by qingtianya-wyt** [wsshin/SellmeierFit.jl#5]
Hi, I have downloaded this package,but I don't know how to install and use it. Could you help me solve it, please?

**Comment by wsshin** [comment]
This is a Julia package.  Like Python packages run on Python, Julia packages run on Julia.  So, you first need to install Julia.  Download and install Julia from https://julialang.org.

Then, run Julia.  In the Julia console (also know as "REPL"), install this package.  The package installation is easy.  Type "]" first.  This will change the prompt from "julia>" to "pkg>".  Then, execute "add SellmeirFit".  

Once the package is installed, you can press the backspace key (or the delete key on Mac) to change the prompt from "pkg>" back to "julia>".  There, execute "using SellmeirFit" to use the package.  Then follow the tutorials in the documentation: https://wsshin.github.io/SellmeierFit.jl/stable/tutorials/.

**Comment by qingtianya-wyt** [comment]
Thanks for your reply, I installed it successfully !

**Comment by wsshin** [comment]
I added installation instructions in the documentation: https://wsshin.github.io/SellmeierFit.jl/stable/install/.

**Comment by qingtianya-wyt** [comment]
> I added installation instructions in the documentation: https://wsshin.github.io/SellmeierFit.jl/stable/install/.
Thanks for your reply. I want to know if I could only fit the first four items and how to set? I am using it to fit the refractive index ,but the final fitting items are different for nx,ny,nz, is there any way to make them have same fitting items?

**Comment by wsshin** [comment]
> Thanks for your reply. I want to know if I could only fit the first four items and how to set? I am using it to fit the refractive index ,but the final fitting items are different for nx,ny,nz, is there any way to make them have same fitting items?

Not sure if I understood your question correctly.  Do you want to use only the first four entries of `λ` and `ε` for fitting?  In that case, you can do
```julia
(; mdl, err) = fit_sellmeier(λ[1:4], ε[1:4])
```
where `λ[1:4]` indicates the first four entries.  If you are familiar with MATLAB, it has the same meaning as MATLAB's `λ(1:4)`.  For example,
```julia-repl
julia> λ = rand(10)
10-element Vector{Float64}:
 0.239345971065126
 0.9996899333161232
 0.5983020822625601
 0.7033539319021145
 0.7510695264576668
 0.7295180496155302
 0.1547636465589396
 0.9956176869728298
 0.09439199224385653
 0.8722232239675407

julia> λ[1:4]
4-element Vector{Float64}:
 0.239345971065126
 0.9996899333161232
 0.5983020822625601
 0.7033539319021145
```

**Comment by qingtianya-wyt** [comment]
Thanks a lot. Maybe there is a misunderstand of my words. Fitting formula used in this code is n=1+(B1*λ*λ) /(λ*λ-C1)+...+(Bi*λ*λ) /(λ*λ-Ci). I want to fit n  with  i=4 in the formula, that means the  fitting formula is n=1+(B1*λ*λ) /(λ*λ-C1)+...+(B4*λ*λ) /(λ*λ-C4).I don't clear if this could be done in this code.

**Comment by wsshin** [comment]
> Fitting formula used in this code is n=1+(B1_λ_λ) /(λ_λ-C1)+...+(Bi_λ_λ) /(λ_λ-Ci). I want to fit n with i=4 in the formula, that means the fitting formula is n=1+(B1_λ_λ) /(λ_λ-C1)+...+(B4_λ_λ) /(λ_λ-C4).

You can achieve this by 
```julia
(; mdl, err) = fit_sellmeier(λ, ε, 4)
```
